### ISSUE TITLE
Parts needing to be renamed

### ISSUE THREAD

**Issue by ghost** [sparkfun/Beefcake_Relay_Control_Kit#3]
R4 needs to be renamed R1 and Q2 needs to be renamed Q1

**Comment by marshalltaylorSFE** [comment]
This is not on the checklist but is probably a good idea for small designs.  Designators updated.

**Comment by ghost** [comment]
"R4 needs to be renamed R1" 

Looks like R4 is now mislabeled R3. Still needs to be renamed R1.

**Comment by marshalltaylorSFE** [comment]
Sure thing
